# Generated by Django 4.0 on 2022-01-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivo',
            name='file',
            field=models.FileField(null=True, upload_to='preventivos'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipos'),
        ),
    ]
