# Generated by Django 4.0 on 2022-01-25 01:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_preventivo_file_alter_equipo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresa')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresa',
            },
        ),
        migrations.AddField(
            model_name='preventivo',
            name='fechasiguiente',
            field=models.DateField(default=datetime.date(2022, 1, 24), max_length=255),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='solicitado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.area'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='subtotalmo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='subtotalpiezas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productospreventivo',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='productostrabajo',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='falla',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='solicitado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.area'),
        ),
        migrations.AlterField(
            model_name='preventivo',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='preventivo',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='productospreventivo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='productostrabajo',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='subtotalmo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='subtotalpiezas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
