# Generated by Django 4.0 on 2022-01-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_empresa_preventivo_fechasiguiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivo',
            name='estado',
            field=models.CharField(choices=[('Programado', 'Programado'), ('En espera', 'En espera'), ('En proceso', 'En proceso'), ('Atrasado', 'Atrasado'), ('Realizado', 'Realizado')], default='Programado', max_length=255),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(choices=[('Programado', 'Programado'), ('En espera', 'En espera'), ('En proceso', 'En proceso'), ('Atrasado', 'Atrasado'), ('Realizado', 'Realizado')], default='Programado', max_length=255),
        ),
    ]
