# Generated by Django 4.0 on 2022-01-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_preventivo_estado_trabajo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivo',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.personal'),
        ),
        migrations.AlterField(
            model_name='preventivo',
            name='solicitado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitado', to='index.personal'),
        ),
    ]
