# Generated by Django 4.0 on 2022-01-27 18:47

import datetime
from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_preventivo_responsable_alter_preventivo_solicitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empresa', validators=[index.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='preventivo',
            name='fechasiguiente',
            field=models.DateField(default=datetime.date(2022, 1, 27), max_length=255),
        ),
        migrations.AlterField(
            model_name='preventivo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
