# Generated by Django 4.0 on 2022-01-27 23:27

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_empresa_imagen_alter_preventivo_fechasiguiente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivo',
            name='fechasiguiente',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipos', validators=[index.models.validate_image_equipo]),
        ),
    ]
