# Generated by Django 4.0 on 2022-01-28 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_remove_preventivo_total_remove_trabajo_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivo',
            name='file',
        ),
        migrations.CreateModel(
            name='HistorialPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=255)),
                ('subtotalpiezas', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('subtotalmo', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('file', models.FileField(null=True, upload_to='preventivos')),
                ('created', models.DateTimeField(auto_now=True)),
                ('preventivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.preventivo')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.personal')),
            ],
            options={
                'verbose_name': 'historial preventivo',
                'verbose_name_plural': 'historial preventivos',
                'order_with_respect_to': 'created',
            },
        ),
    ]
