# Generated by Django 4.0 on 2022-01-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_preventivo_file_historialpreventivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpreventivo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='preventivos'),
        ),
    ]
