# Generated by Django 4.0 on 2022-01-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_historialpreventivo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpreventivo',
            name='fecha_programada',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historialpreventivo',
            name='horas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='historialpreventivo',
            name='solicitadoh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitadoh', to='index.personal'),
        ),
        migrations.AddField(
            model_name='historialpreventivo',
            name='supervisadoh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisadoh', to='index.personal'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='supervisadop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisadop', to='index.personal'),
        ),
    ]
