# Generated by Django 4.0 on 2022-02-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_historialpreventivo_fecha_programada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productospreventivo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
