# Generated by Django 4.0 on 2022-02-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_productospreventivo_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajo',
            options={'verbose_name': 'correctivo', 'verbose_name_plural': 'correctivos'},
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='realizado',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='solicitado',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='responsablec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsablec', to='index.personal'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='solicitadoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitadoc', to='index.personal'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='supervisadoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisadoc', to='index.personal'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
