# Generated by Django 4.0 on 2022-02-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_trabajo_options_remove_trabajo_realizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='falla',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='HistorialCorrectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=255)),
                ('fecha_programada', models.DateField(max_length=255, null=True)),
                ('subtotalpiezas', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('subtotalmo', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('horas', models.IntegerField(default=0, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='correctivos')),
                ('created', models.DateTimeField(auto_now=True)),
                ('correctivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.trabajo')),
                ('responsablehc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsablehc', to='index.personal')),
                ('solicitadohc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitadohc', to='index.personal')),
                ('supervisadohc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisadohc', to='index.personal')),
            ],
            options={
                'verbose_name': 'historial correctivo',
                'verbose_name_plural': 'historial correctivos',
                'order_with_respect_to': 'created',
            },
        ),
    ]
