# Generated by Django 4.0 on 2022-02-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_trabajo_falla_alter_trabajo_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productostrabajo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='productostrabajo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
