# Generated by Django 4.0 on 2022-03-02 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_productostrabajo_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.area'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
