# Generated by Django 4.0 on 2022-05-25 23:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_alter_equipo_imagen_alter_personal_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='imagen',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[100, 100], upload_to='empresa'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[300, 400], upload_to='equipos'),
        ),
    ]
