# Generated by Django 4.0 on 2022-05-25 23:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_alter_empresa_imagen_alter_equipo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[400, 300], upload_to='equipos'),
        ),
    ]
