# Generated by Django 4.0 on 2022-05-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_equipo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='herramientas')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ultimo_uso', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'herramienta',
                'verbose_name_plural': 'herramientas',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.CreateModel(
            name='HistorialHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('correctivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.trabajo')),
                ('preventivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.preventivo')),
            ],
            options={
                'verbose_name': 'historial herramienta',
                'verbose_name_plural': 'historial herramientas',
            },
        ),
    ]
