# Generated by Django 4.0 on 2022-05-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_herramienta_alter_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='ultimo_uso',
        ),
        migrations.AddField(
            model_name='preventivo',
            name='herramientas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='herramientas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
