# Generated by Django 4.0 on 2022-05-27 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_remove_herramienta_ultimo_uso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialherramienta',
            name='fecha',
        ),
        migrations.AddField(
            model_name='historialherramienta',
            name='herramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.herramienta'),
        ),
    ]
